# version: '3.9'

services:
  drupal:
    image: drupal:10.4
    container_name: drupal_sis
    restart: always
    ports:
      - "8080:80"
    volumes:
    # Drupal file storage
      # Core and custom files
      - ./drupal/sites/default/settings.php:/var/www/html/sites/default/settings.php
      - ./drupal/sites/default/private:/var/www/html/sites/default/private
      - ./drupal/sites/default/files:/var/www/html/sites/default/files
      # Mods and Themes
      - ./local/modules/custom:/var/www/html/modules/custom
      - ./drupal/modules/contrib:/var/www/html/modules/contrib
      - ./local/themes/custom:/var/www/html/themes/custom
      - ./drupal/themes/contrib:/var/www/html/themes/contrib
    # Drupal import files
      - ./local/import/db_backups:/db_backups
      - ./local/import/config/sync:/var/www/html/config/sync
    # Scripts
      - ./local/startup.sh:/startup.sh  # For startup script
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_NAME=gis_sis
      - DRUPAL_DATABASE_USER=gis_sis_user
      - DRUPAL_DATABASE_PASSWORD=user_240885MP
    depends_on:
      - db
    networks:
      - drupal-network

  db:
    image: mariadb:10.5
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_DATABASE: gis_sis
      MYSQL_USER: gis_sis_user
      MYSQL_PASSWORD: user_240885MP
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal-network
volumes:
  db_data:

networks:
  drupal-network:
