version: '3.8'

services:
  drupal:
    image: drupal:10
    container_name: drupal_dev
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./web:/var/www/html
      - ./startup.sh:/var/www/html/startup.sh
    depends_on:
      - db
    environment:
      - DRUPAL_DB_HOST=db
      - DRUPAL_DB_USER=drupal
      - DRUPAL_DB_PASSWORD=drupal
      - DRUPAL_DB_NAME=drupal
    command: ["sh", "-c", "/var/www/html/startup.sh && apache2-foreground"]

  db:
    image: mariadb:10.5
    container_name: mariadb_dev
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=drupal
      - MYSQL_USER=drupal
      - MYSQL_PASSWORD=drupal
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
