# version: '3.9'

services:
  drupal:
    image: drupal:10.4
    container_name: drupal_sis
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./modules/custom:/var/www/html/modules/custom
      - ./modules/contrib:/var/www/html/modules/contrib
      - ./db_backups:/db_backups
      - ./themes/custom:/var/www/html/themes/custom
      - ./themes/contrib:/var/www/html/themes/contrib
      - ./config/sync:/var/www/html/config/sync
      - ./translations:/var/www/html/sites/default/files/translations
      - ./sites/default/files:/var/www/html/sites/default/files
      - ./sites/default/settings.php:/var/www/html/sites/default/settings.php
      - ./sites/default/private:/var/www/html/sites/default/private
      - ./startup.sh:/startup.sh  # <-- Add this line to map the script
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_NAME=gis_sis
      - DRUPAL_DATABASE_USER=gis_sis_user
      - DRUPAL_DATABASE_PASSWORD=user_240885MP
    depends_on:
      - db
    networks:
      - drupal-network

  db:
    image: mariadb:10.5
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_DATABASE: gis_sis
      MYSQL_USER: gis_sis_user
      MYSQL_PASSWORD: user_240885MP
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - drupal-network

#   tools:
#     image: drupal:10.4
#     container_name: drupal_tools
#     volumes:
#       - ./modules/custom:/var/www/html/modules/custom
#       - ./themes/custom:/var/www/html/themes/custom
#       - ./config/sync:/var/www/html/config/sync
#       - ./translations:/var/www/html/sites/default/files/translations
#       - ./sites/default/files:/var/www/html/sites/default/files
#       - ./sites/default/settings.php:/var/www/html/sites/default/settings.php
#       - ./sites/default/private:/var/www/html/sites/default/private
#       - ./startup.sh:/startup.sh  # <-- Add this line to map the script
#     working_dir: /var/www/html
#     networks:
#       - drupal-network
#     entrypoint: ["tail", "-f", "/dev/null"]  # Keeps the container running

volumes:
  db_data:

networks:
  drupal-network:
