version: '3.8'

services:
  drupal:
    image: drupal:10.4
    container_name: drupal_sis
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./custom_modules:/var/www/html/modules/custom
      - ./custom_themes:/var/www/html/themes/custom
      - ./config/sync:/var/www/html/config/sync
      - ./translations:/var/www/html/sites/default/files/translations
      - ./sites/default/files:/var/www/html/sites/default/files
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_NAME=gis_sis
      - DRUPAL_DATABASE_USER=gis_sis_user
      - DRUPAL_DATABASE_PASSWORD=user_240885MP
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: drupal_db
    restart: always
    environment:
      MYSQL_DATABASE: gis_sis
      MYSQL_USER: gis_sis_user
      MYSQL_PASSWORD: user_240885MP
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
