version: '3.8'

services:
  drupal:
    image: drupal:10.4-apache  # ✅ Use a pre-installed image
    container_name: drupal
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - mariadb
    volumes:
      - ./config/sync:/var/www/html/config/sync  # ✅ Config persistence
      - ./modules:/var/www/html/modules  # ✅ Modules persistence
      - ./themes:/var/www/html/themes  # ✅ Themes persistence
      - drupal_files:/var/www/html/sites/default/files  # ✅ User uploads persistence
    environment:
      - DRUPAL_DB_HOST=mariadb
      - DRUPAL_DB_USER=${MYSQL_USER}
      - DRUPAL_DB_PASSWORD=${MYSQL_PASSWORD}
      - DRUPAL_DB_NAME=${MYSQL_DATABASE}

  mariadb:
    image: mariadb:10.6
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_files:
  db_data:
